version: '3'
services:
  node-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4444:4444"
    environment:
      - JWT_SECRET=thisisshortie
      - MONGODB_URL="mongodb+srv://omkar:Omkar%40123@cluster0.xhkbi.mongodb.net/Shortie?retryWrites=true&w=majority"