apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortie
spec:
  selector:
    matchLabels:
      app: shortie
  template:
    metadata:
      labels:
        app: shortie
    spec:
      containers:
      - name: shortie
        image: vaibhavgawad/shortie:1
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: shortie
spec:
  selector:
    app: shortie
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4000
  type: LoadBalancer
